server:
  port: 8081
spring:
  application:
    name: app
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/${spring.application.name}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    liquibase:
      change-log: classpath:/db/master.yaml
      user: root
      password:
      contexts: dev, faker
      clear-check-sums: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
  graphql:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET, POST, OPTIONS
      allowed-headers: content-type, authorization
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    base64-secret: ZTY3ZWUwMTM4ZWNlMGEwNTE0YTBhZDQwNzY3NGVmNzc0OWExNTY5ZGZmZGIxODAwNjQwY2Q3ZjJjY2JjODU4NWY3OGU0YzQxNmFmN2VjYjQxOTM4ZDU1MzY4M2ZmY2Y3MTFjN2M2NDdiMTVjNjY0NzM2M2M4YWZlYTg3MTAyMTY=
    token-validity-in-seconds: 86400 # 24 hours
    token-validity-in-seconds-for-remember-me: 2592000 # 30 days
cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: content-type, authorization
  exposed-headers: authorization
  allow-credentials: true
  max-age: 1800

clientApp:
  name: app

